### PR TITLE
Kubtest agents for k8s jobs 

### PR DESCRIPTION
**Pull request by jasmingacic**
added curl, cypress and postman agents
on POST executions/ the executor will spin up respective k8s jobs
TODO: still need to figure out the way how to dynamically load images and parameters

Signed-off-by: Jasmin Gacic <jasmin.gacic@gmail.com>

Since this is implemented as an executor it doesn't have much ability to make "smart" decisions based on requests.

I'd like to hear more input on design and other related stuff

### CODE REVIEW

**Review by nicufk — APPROVED** [review]
LGTM

**Comment by jasmingacic** [comment]
One major question is how to normalize expected input across all agents:

Cypress:
```
# go run agents/cypress-agent/main.go -h
kubtest

Usage:
  kubtest [flags]

Flags:
  -b, --branch string       branch
  -h, --help                help for kubtest
  -i, --id string           input script
  -p, --path string         path
  -r, --repository string   repository path
  -s, --script string       input script
```

cUrl
```
# go run agents/curl-agent/main.go -h
kubtest

Usage:
  kubtest [flags]

Flags:
  -h, --help                     help for kubtest
  -i, --id string                input script
  -p, --parameters stringArray   input script
  -r, --repository string        repository path
  -s, --script string            input script
```
postman:
```
# go run agents/postman-agent/main.go -h
kubtest

Usage:
  kubtest [flags]

Flags:
  -h, --help                     help for kubtest
  -i, --id string                input script
  -p, --parameters stringArray   input script
  -r, --repository string        repository path
  -s, --script string            input script
```

Ideally it should be something where each of agents accepts only one parameter `--script` in form of JSON (kubtest.Execution) and then we deserialize it into an object when invoking the agent. 

Please chime in with ideas

**Comment by exu** [comment]
> One major question is how to normalize expected input across all agents:

I would go with `stdin` and `stdout` JSON based in/out: 
- input - structs are ready - no need to mess with flags 
- output - structs are ready to use
so almost no work to do 
 
same code as in http based executor. 
same validations etc. 

Additionally we can provide those structs for other clients

**Comment by olensmar** [comment]
I'm thinking that a generic ExcecutionRequest (in json format) would contain the following:
- script | scriptRef
  - scriptRef can be a URL or a repository/folder/branch reference
     - repository can be of various types (git, subversion, etc) with different parameters, we only support git to start with
  - credentials - optional - for scriptRefs that require some kind of credentials (username/pwd, token, etc)
  - script would be a string
- parameters (NV-pairs) 

Not sure anything else is needed to start with?

We should provide some kind of library to resolve scriptRefs - so that users don't have to implement that themselves (unless they want to), i.e. a method
- resolveScriptRef( ScriptRef ) - which would return a folder containing the referenced script

We should also provide a generic way for executors to return multi-file responses - i.e. videos, screenshots, etc... perhaps the initial json result could contain an optional list of files (name, type, description) - which can then be retrieved from the executor with 

/executions/{executionId}/files/{fileId} 

it would be up to the executor to store these files temporarily - kubtest would store them in some persistent storage (configurable - S3, etc)

all would be defined in OpenAPI - so implementors can generate server stubs in any language they want

**Pull request closed without merging**
